spring:
  application:
    name: orchestrator-service

  cloud:
    config:
      enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: witchblog
    password: 40c57b33ae35449a990ebd90976ad69d
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: orchestrator

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: orchestrator

  sql:
    init:
      platform: postgres
      mode: always
      schema-locations: classpath:schema.sql

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: localhost

server:
  port: 8083

common:
  consumer:
    topic: orchestrator
    group-id: orchestrator-group