spring:
  application:
    name: orchestrator-service


eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://registry-service:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: orchestrator-service
