version: '3.8'

services:
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    networks:
      - kafka-net
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      ALLOW_PLAINTEXT_LISTENER: "yes"
    restart: unless-stopped

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: "witchblog"
      POSTGRES_PASSWORD: "40c57b33ae35449a990ebd90976ad69d"
    ports:
      - "5432:5432"

networks:
  kafka-net:
    name: kafka-net
