spring:
  application:
    name: product-service
  kafka:
    bootstrap-servers: localhost:9092
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: witchblog
    password: 40c57b33ae35449a990ebd90976ad69d
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: payment
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: payment
  sql:
    init:
      platform: postgres
      mode: always
      schema-locations: classpath:schema.sql

management:
  endpoint:
    health:
      show-details: "ALWAYS"

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: localhost

server:
  port: 8086

common:
  consumer:
    topic: payment
    group-id: payment-group

blik-service: success
