package org.common.eventing.gpt.tarot;

import java.util.List;

public class TarotCardsLookupTable {
    public static final List<TarotCard> tarotCards = List.of(
            // Wielkie Arkana (Major Arcana)
            new TarotCard("0. Głupiec", "Nowy początek, wolność, spontaniczność."),
            new TarotCard("I. Mag", "Wola, moc, inicjatywa."),
            new TarotCard("II. Kapłanka", "Intuicja, tajemnice, duchowość."),
            new TarotCard("III. Cesarzowa", "Obfitość, płodność, natura."),
            new TarotCard("IV. Cesarz", "Autorytet, struktura, kontrola."),
            new TarotCard("V. Kapłan", "Tradycja, duchowość, wiedza."),
            new TarotCard("VI. Kochankowie", "Związki, wybory, harmonia."),
            new TarotCard("VII. Rydwan", "Zwycięstwo, determinacja, ruch."),
            new TarotCard("VIII. Sprawiedliwość", "Równowaga, prawda, uczciwość."),
            new TarotCard("IX. Pustelnik", "Refleksja, samotność, poszukiwanie."),
            new TarotCard("X. Koło Fortuny", "Los, zmiana, cykle."),
            new TarotCard("XI. Siła", "Odwaga, wewnętrzna moc, cierpliwość."),
            new TarotCard("XII. Wisielec", "Poświęcenie, nowe spojrzenie, stagnacja."),
            new TarotCard("XIII. Śmierć", "Transformacja, koniec, odrodzenie."),
            new TarotCard("XIV. Umiarkowanie", "Równowaga, umiar, harmonia."),
            new TarotCard("XV. Diabeł", "Zależność, materializm, pokusa."),
            new TarotCard("XVI. Wieża", "Nagła zmiana, wstrząs, przebudzenie."),
            new TarotCard("XVII. Gwiazda", "Nadzieja, inspiracja, uzdrowienie."),
            new TarotCard("XVIII. Księżyc", "Iluzja, lęk, podświadomość."),
            new TarotCard("XIX. Słońce", "Radość, sukces, optymizm."),
            new TarotCard("XX. Sąd Ostateczny", "Odpowiedzialność, przebudzenie, osąd."),
            new TarotCard("XXI. Świat", "Pełnia, spełnienie, podróż."),

            // Małe Arkana – Buławy (Wands)
            new TarotCard("As Buław", "Nowe możliwości, pasja, inspiracja."),
            new TarotCard("Dwójka Buław", "Plany, decyzje, odkrywanie."),
            new TarotCard("Trójka Buław", "Rozwój, postęp, wizja."),
            new TarotCard("Czwórka Buław", "Świętowanie, harmonia, sukces."),
            new TarotCard("Piątka Buław", "Konflikt, rywalizacja, napięcie."),
            new TarotCard("Szóstka Buław", "Zwycięstwo, uznanie, nagroda."),
            new TarotCard("Siódemka Buław", "Obrona, determinacja, przewaga."),
            new TarotCard("Ósemka Buław", "Ruch, wiadomości, tempo."),
            new TarotCard("Dziewiątka Buław", "Wytrwałość, ochrona, zmęczenie."),
            new TarotCard("Dziesiątka Buław", "Obciążenie, odpowiedzialność, presja."),
            new TarotCard("Paź Buław", "Eksploracja, nauka, entuzjazm."),
            new TarotCard("Rycerz Buław", "Akcja, podróż, odwaga."),
            new TarotCard("Królowa Buław", "Pewność siebie, niezależność, pasja."),
            new TarotCard("Król Buław", "Przywództwo, wizja, siła woli."),

            // Małe Arkana – Puchary (Cups)
            new TarotCard("As Pucharów", "Miłość, uczucia, nowe relacje."),
            new TarotCard("Dwójka Pucharów", "Partnerstwo, zgoda, połączenie."),
            new TarotCard("Trójka Pucharów", "Przyjaźń, świętowanie, wspólnota."),
            new TarotCard("Czwórka Pucharów", "Apatia, znudzenie, refleksja."),
            new TarotCard("Piątka Pucharów", "Strata, żal, rozczarowanie."),
            new TarotCard("Szóstka Pucharów", "Wspomnienia, nostalgia, dzieciństwo."),
            new TarotCard("Siódemka Pucharów", "Iluzje, wybory, marzenia."),
            new TarotCard("Ósemka Pucharów", "Porzucenie, rezygnacja, poszukiwanie."),
            new TarotCard("Dziewiątka Pucharów", "Spełnienie, przyjemność, zadowolenie."),
            new TarotCard("Dziesiątka Pucharów", "Szczęście, harmonia, rodzina."),
            new TarotCard("Paź Pucharów", "Romantyzm, wiadomości, delikatność."),
            new TarotCard("Rycerz Pucharów", "Idealizm, propozycja, uczuciowość."),
            new TarotCard("Królowa Pucharów", "Wrażliwość, empatia, intuicja."),
            new TarotCard("Król Pucharów", "Doświadczenie, opanowanie, mądrość."),

            // Małe Arkana – Miecze (Swords)
            new TarotCard("As Mieczy", "Jasność, prawda, intelekt."),
            new TarotCard("Dwójka Mieczy", "Decyzja, blokada, równowaga."),
            new TarotCard("Trójka Mieczy", "Złamane serce, smutek, rozstanie."),
            new TarotCard("Czwórka Mieczy", "Odpoczynek, regeneracja, introspekcja."),
            new TarotCard("Piątka Mieczy", "Konflikt, zdrada, napięcie."),
            new TarotCard("Szóstka Mieczy", "Przejście, zmiana, ulga."),
            new TarotCard("Siódemka Mieczy", "Oszustwo, strategia, skrytość."),
            new TarotCard("Ósemka Mieczy", "Uwięzienie, ograniczenia, lęk."),
            new TarotCard("Dziewiątka Mieczy", "Lęk, niepokój, koszmary."),
            new TarotCard("Dziesiątka Mieczy", "Koniec, zdrada, porażka."),
            new TarotCard("Paź Mieczy", "Ciekawość, czujność, nauka."),
            new TarotCard("Rycerz Mieczy", "Impulsywność, szybkość, determinacja."),
            new TarotCard("Królowa Mieczy", "Analiza, obiektywizm, prawda."),
            new TarotCard("Król Mieczy", "Władza, intelekt, sprawiedliwość."),

            // Małe Arkana – Monety (Pentacles)
            new TarotCard("As Monet", "Nowe możliwości, zasoby, materialność."),
            new TarotCard("Dwójka Monet", "Balans, adaptacja, wybory."),
            new TarotCard("Trójka Monet", "Współpraca, umiejętności, osiągnięcia."),
            new TarotCard("Czwórka Monet", "Zachowawczość, kontrola, stabilność."),
            new TarotCard("Piątka Monet", "Brak, trudności, wykluczenie."),
            new TarotCard("Szóstka Monet", "Dawanie i branie, hojność, pomoc."),
            new TarotCard("Siódemka Monet", "Cierpliwość, inwestycje, oczekiwanie."),
            new TarotCard("Ósemka Monet", "Praca, rozwój, doskonalenie."),
            new TarotCard("Dziewiątka Monet", "Niezależność, dostatek, samowystarczalność."),
            new TarotCard("Dziesiątka Monet", "Rodzina, dziedzictwo, stabilizacja."),
            new TarotCard("Paź Monet", "Możliwości, nauka, stabilny rozwój."),
            new TarotCard("Rycerz Monet", "Rutyna, odpowiedzialność, systematyczność."),
            new TarotCard("Królowa Monet", "Ziemskość, bezpieczeństwo, opiekuńczość."),
            new TarotCard("Król Monet", "Bogactwo, sukces, przewidywalność.")
    );
}
